CREATE TABLE IF NOT EXISTS "Users"
(
    "user_id"       INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    "username"      varchar(50),
    "email"         varchar(100),
    "password_hash" varchar(255),
    "google_id"     varchar(255),
    "created_at"    timestamp DEFAULT CURRENT_TIMESTAMP,
    "updated_at"    timestamp DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS "Tasks"
(
    "task_id"     INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    "user_id"     integer,
    "title"       varchar(255),
    "status"      varchar(100) DEFAULT 'NOT_STARTED',
    "description" varchar(255),
    "due_date"    timestamp,
    "updated_at"  timestamp DEFAULT CURRENT_TIMESTAMP,
    "created_at"  timestamp DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS "Categories"
(
    "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    "user_id"     integer,
    "name"        varchar(100),
    "created_at"  timestamp DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS "Task_Categories"
(
    "task_id"     integer,
    "category_id" integer,
    "created_at"  timestamp DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamp DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Tasks"
    ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Categories"
    ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Task_Categories"
    ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("category_id");

ALTER TABLE "Task_Categories"
    ADD FOREIGN KEY ("task_id") REFERENCES "Tasks" ("task_id");
